from enum import Enum


class EventType(str, Enum):
    # Identity lifecycle
    USER_CREATED = "USER_CREATED"
    USER_TERMINATED = "USER_TERMINATED"
    ROLE_ASSIGNED = "ROLE_ASSIGNED"
    ROLE_REMOVED = "ROLE_REMOVED"

    # Access governance
    ACCESS_REQUESTED = "ACCESS_REQUESTED"
    ACCESS_APPROVED = "ACCESS_APPROVED"
    ACCESS_REJECTED = "ACCESS_REJECTED"
    ACCESS_PROVISIONED = "ACCESS_PROVISIONED"
    ACCESS_REVOKED = "ACCESS_REVOKED"
    SOD_VIOLATION = "SOD_VIOLATION"
    ACCESS_REVIEW_COMPLETED = "ACCESS_REVIEW_COMPLETED"

    # PAM
    PRIVILEGED_CHECKOUT = "PRIVILEGED_CHECKOUT"
    PRIVILEGED_SESSION_STARTED = "PRIVILEGED_SESSION_STARTED"
    PRIVILEGED_SESSION_ENDED = "PRIVILEGED_SESSION_ENDED"
    PRIVILEGE_EXPIRED = "PRIVILEGE_EXPIRED"

    # Authentication / authorization (used from Phase 3)
    LOGIN_SUCCEEDED = "LOGIN_SUCCEEDED"
    LOGIN_FAILED = "LOGIN_FAILED"
    ACCESS_DENIED = "ACCESS_DENIED"


class Result(str, Enum):
    SUCCESS = "SUCCESS"
    DENIED = "DENIED"  # a policy or authorization decision said no
    FAILURE = "FAILURE"  # something went wrong (bad input, conflict, not found)